routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl();
    $parse_url = parse_url($referer, PHP_URL_PATH);
    $segments = explode('/', $parse_url);
    if (in_array($segments[1], config()->get('app.locales')) || $segments[1]=='') {
        unset($segments[1]);
    } 
    if ($lang != config()->get('app.locale')){ 
        array_splice($segments, 1, 0, $lang); 
    }
    $url = Request::root().implode("/", $segments);
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url);
})->name('setlocale');


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale(), 'middleware'=>'offline' ], function(){

    Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);

    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'isAdmin']], function() {
        Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
        Route::match(['get', 'post'],'users/message/{id}',    ['as'=>'users.message', 'uses'=>'UserController@message']);
        Route::get('users/download/{id}', ['as' => 'users.download', 'uses' => 'UserController@download']);
        Route::get('users/quiz/{id}', ['as' => 'users.quiz', 'uses' => 'UserController@quiz']);
        Route::get('users/removetestsprogress/{id}', ['as' => 'users.removetestsprogress', 'uses' => 'UserController@removeTestsProgress']);
        Route::resource('users' , 'UserController');
        Route::post('groups/detail', ['as' => 'groups.detail', 'uses' => 'GroupController@detail']);
        Route::get('groups/stat/{id}', ['as' => 'groups.stat', 'uses' => 'GroupController@stat']);
        Route::get('groups/webquestions/{id}', ['as' => 'groups.webquestions', 'uses' => 'GroupController@webquestions']);
        Route::resource('groups', 'GroupController');
        Route::resource('roles' , 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
        Route::resource('pages', 'PageController');

        Route::post( 'medias/upload', ['as'=>'medias.upload', 'uses'=>'MediaController@upload'] );
        Route::resource('medias', 'MediaController');
        Route::resource('glossaries', 'GlossaryController');
        Route::resource('mailings', 'MailingController');

        Route::resource('courses', 'CourseController');
        Route::resource('modules', 'ModuleController');
        Route::resource('lessons', 'LessonController');
        Route::resource('themes', 'ThemeController');
        Route::resource('questions', 'QuestionController');
        Route::resource('quizzes', 'QuizController');

        Route::post('/run', ['as' => 'run', 'uses' => 'AdminController@run']);
        Route::match(['get', 'post'],'/settings',  ['as'=>'settings', 'uses'=>'AdminController@settings']);
        Route::match(['get', 'post'],'/tracks',    ['as'=>'tracks',   'uses'=>'AdminController@tracks']);
        Route::post('/tracklist', ['as' => 'tracklist', 'uses' => 'AdminController@tracklist']);
        Route::get('/phpinfo', ['as' => 'phpinfo', 'uses' => 'AdminController@phpinfo']);
        // Route::get('/offline', ['as' => 'offline', 'uses' => 'AdminController@offline']);
        // Route::get('/offline/offlineCopy', ['as' => 'offlineCopy', 'uses' => 'AdminController@offlineCopy']);
    });

    # роуты для студентов

        Route::match(['get', 'post'], '/profile', ['as' => 'profile', 'middleware' => ['auth'],'uses' => 'UserController@profile']);
        Route::match(['get', 'post'], '/message', ['as' => 'message', 'middleware' => ['auth'],'uses' => 'UserController@message']);

        Route::group(['middleware' => ['auth', 'isActive', 'activity']], function() {
            Route::get('/module/{id}', ['as' => 'moduleshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@moduleshow']);
            Route::get('/theme/{id}', ['as' => 'themeshow', 'middleware' => ['isOpenTheme'],'uses' => 'UserController@themeshow']);
            Route::post('/open-next-theme', ['as' => 'opennexttheme', 'uses' => 'UserController@openNextTheme']);
            Route::get('/exam/{id}', ['as' => 'examshow', 'middleware' => [],'uses' => 'UserController@examshow']);
            Route::post('/examcheck/{id}', ['as' => 'examcheck', 'middleware' => [],'uses' => 'UserController@examcheck']);
            Route::get('/test/{id}', ['as' => 'testshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testshow']);
            Route::post('/testcheck/{id}', ['as' => 'testcheck', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testcheck']);
            Route::match(['get', 'post'], '/webquestions/{id?}', ['as' => 'webquestions', 'middleware' => [],'uses' => 'UserController@webquestions']);
            Route::match(['get', 'post'], '/homework/{id?}', ['as' => 'homework', 'middleware' => [],'uses' => 'UserController@homework']);
            Route::match(['get', 'post'], '/quiz/{id?}', ['as' => 'quizshow', 'middleware' => [],'uses' => 'UserController@quizshow']);
            Route::get('/pdf/{id}', ['as' => 'pdf', 'uses' => 'UserController@pdf']);

        });

        Route::post('/pushcounter', ['as' => 'pushcounter', 'uses' => 'UserController@pushcounter']);

    # регистрации и авторизации

        Auth::routes();
        Route::post( '/register', ['as'=>'register', 'uses'=>'GeneralController@postRegister'] );
        Route::post( '/logout',  ['as'=>'logout', 'uses'=>'GeneralController@logout'] );

    # различные страницы

        Route::get('/glossary/{character?}', ['as' => 'glossary', 'uses' => 'GeneralController@glossary']);
        Route::group(['prefix' => 'page'], function() {
            Route::get('/{page_slug}', ['as'=>'page', 'uses'=>'GeneralController@pageshow']);
        });
});

app/Mailing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Mail\OrderShipped;
use Illuminate\Support\Facades\Mail;

class Mailing extends Model
{

    protected $dates = ['date_send'];

    protected $guarded = [];

    public function group()
    {
        return $this->belongsTo('App\Group');
    }

    public function send()
    {
        foreach ($this->group->users as $key => $user) {
            $to = $user->email;
            $data = [
                'subject' => $this->name,
                'message' => $this->content,
            ];
            Mail::to( $to )->send(new OrderShipped($data));
        }
        $this->sent = true;
        $this->save();        
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Traits\BreadcrumbTrait;

use App\Mail\OrderShipped;
use Illuminate\Support\Facades\Mail;

use App\User;
use App\Group;
use App\Media;
use App\Module;
use App\Option;
use App\Track;
use App\Page;
use App\Theme;
use Auth;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Storage;
use ZipArchive;

use Session;

class AdminController extends Controller 
{ 

    use BreadcrumbTrait;

    public function index()
    {
        return view('dashboard.index', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function run(Request $request)
    {
        $module = Module::findOrFail($request->module_id);
        $group_id  = $request->group_id  ? $request->group_id  : 0;
        $array = [];
        if ($module && $group_id) {
            # вытаскиваем все имеющиеся группы группы
                foreach ($module->groups as $key => $group) {
                    $array[$group->id] = [
                        'date_start'=>$group->pivot->date_start,
                        'date_finish'=>$group->pivot->date_finish,
                        'notificated'=>$group->pivot->notificated,
                    ];
                }
            # добавляем или меняем данные з формы
                if ( Carbon::parse($request->date_finish)->lt(Carbon::now()) ) {
                    unset($array[$group_id]);
                    # отправляем всем пользователям письма об остановке модуля
                        if (Option::getOption('mailModuleStop')){
                            $group = Group::find($group_id);
                            if ($group){
                                foreach ($group->users as $key => $user) {
                                    $to = $user->email;
                                    $data = [
                                        'subject' => __('Module stop'),
                                        'module' => $module->name,
                                    ];
                                    Mail::to( $to )->send(new OrderShipped($data));
                                }
                            }
                        }
                } else {
                    $array[$group_id] = [
                        'date_start'=>$request->date_start,
                        'date_finish'=>$request->date_finish,
                        'notificated'=>false,
                    ];
                    # отправляем всем пользователям письма о запуске (изменении строков работы) модуля
                        if (Option::getOption('mailModuleStop')){
                            $group = Group::find($group_id);
                            if ($group){
                                foreach ($group->users as $key => $user) {
                                    $to = $user->email;
                                    $data = [
                                        'template' => 'runmodule',
                                        'subject' => __('Module start'),
                                        'module' => $module->name,
                                        'date_start'=>$request->date_start,
                                        'date_finish'=>$request->date_finish,
                                    ];
                                    Mail::to( $to )->send(new OrderShipped($data));
                                }
                            }
                        }
                }
            # смнхронизируем
                $module->groups()->sync( $array );
            # предоставление доступа пользователям
                $group = Group::findOrFail($group_id);
                $group->openThemesForUsers();
            \App\Track::message(['moduleName'=>$module->name, 'groupName'=>$group->name, 'date1'=>$request->date_start, 'date2'=>$request->date_finish]);        
        }
        echo json_encode([
            'module_id'=>$request->module_id,
            'date_start'=>$group->getDateStart($request->module_id),
            'date_finish'=>$group->getDateFinish($request->module_id),
            'active'=>$group->ifModuleActive($request->module_id),
        ]);
    }


    public function settings(Request $request)
    {
        if ($request->isMethod('post')) {
            foreach ($request->all() as $key => $value) {
                Option::setOption($key, $value ? $value : '');
            }
            \App\Track::message();
            return redirect()->route('settings')
                ->with('flash_message', __('Settings updated successfully'));
        }        
        return view('dashboard.settings', [
            'documents' => Media::where('type','=','application')->get(),
            'users' => User::get(),
            'options' => Option::pluck('value','key'),
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function tracks(Request $request)
    {
        if ($request->isMethod('post')) {
            Track::truncate();
            \App\Track::message();
            return redirect()->route('tracks')
                ->with('flash_message', __('Event Log was cleared'));
        }        
        return view('dashboard.tracks', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function tracklist(Request $request)
    {
        $where = [];
        $columns = [
            0 => 'created_at',
            1 => 'user_id',
            2 => 'ip',
            3 => 'name',
        ];

        $totalData = Track::where($where)->count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if(empty($request->input('search.value'))){
            $temp = Track::where($where)->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $totalFiltered = $totalData;
        } else {
            $search = $request->input('search.value');
            $temp = Track::where($where)->where('name','like',"%{$search}%")
                ->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $temp = Track::where($where)->where('name','like',"%{$search}%");
                $totalFiltered = $temp->count();
        }
        
        $data = [];
        if($models){
            foreach($models as $model){
                $nestedData['date'] = $model->created_at->format('d.m.Y H:i:s');
                $user = User::find($model->user_id);
                $nestedData['user'] = $model->user_id==-1 ? __('System') : ($user ? $user->name : __('Unknown'));
                $nestedData['ip'] = $model->ip;
                $nestedData['name'] = $model->name;
                $data[] = $nestedData;
            }
        }
        $json_data = [
            "draw" => (int)$request->input('draw'),
            "recordsTotal" => (int)$totalData,
            "recordsFiltered" => (int)$totalFiltered,
            "data" => $data,

        ];
        echo json_encode($json_data);
    }

    # делаем правильную ссылку для оффлайна
    function offlineUri($uri = '', $prefix = '')
    {
        $result = $uri;
        $base_url = route('home');
        $new_uri  = str_replace($base_url, '', $uri);
        if ($uri != $new_uri){
            $links = explode('/',$new_uri);
            if (count($links)==1) {$new_uri='index';}
            if (strpos($new_uri, '.') === false) {$new_uri .= '.html';}
            if (substr($new_uri,0,1)=='/') {$new_uri=substr($new_uri,1);}
            $result = $prefix . $new_uri;
        }
        return $result;
    }

    # получение контента по урлу
    public function getDataFromUrl($url, $level=0)
    {
        # получаем данные из файла
            $opts = [
                'http' => [
                    'method' => "GET",
                    'header' => "Accept-language: ".\App::getLocale()."\r\n"
                ]
            ];
            $context = stream_context_create($opts);
            for ($i=0; $i < 10; $i++) { 
                $html_request = @file_get_contents($url, false, $context);
                if ($html_request!==false){
                    break;
                }
            }
        # создаем префикс
            $prefix = '';
            for ($i=0; $i < $level; $i++) { 
                $prefix .= '../';
            }
        # меняем пути для ассетов
            $source  = [ '/css/', '/assets/', '/js/', '../../../storage', '/storage/' ];
            $replace = [ $prefix . 'css/', $prefix . 'assets/', $prefix . 'js/', $prefix . 'storage/', $prefix . 'storage/' ];
            $result = str_replace($source, $replace, $html_request);
        # находи все ссылки и меняем их на локальные, 
            preg_match_all('|href="([^"]*)"|U',$result,$matches); # простые ссылки
            foreach ($matches[1] as $key => $match) {
                $matches[2][$key] = 'href="' . $this->offlineUri($match,$prefix) . '"';
                $result = str_replace($matches[0][$key], $matches[2][$key], $result);
            }

        return $result;
    }

    # phpinfo
    public function phpinfo()
    {
        return view('dashboard.phpinfo', [
            'data' => self::getBreadcrumb(),
        ]);
    }

}

resources/views/dashboard/mailings/form.blade.php
@extends('layouts.admin-layout')

@section('content')

{{ Form::model($model, array('url' => $model->id ? route('mailings.update', $model->id) : route('mailings.store'), 'method' => $model->id ? 'PUT' : 'POST')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header bg-transparent header-elements-inline">
                <h5 class="card-title">@lang('Parameters')</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    {{ Form::label('name', __('Name'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::text('name', null, array('class' => 'field form-control')) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('group_id', __('Group'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::select('group_id', $groups, isset($model->group_id) ? $model->group_id : 0, array('class' => 'field form-control')) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('date_send', __('Date Send'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::date('date_send', isset($model->date_send) ? $model->date_send : null, array('class' => 'field form-control')) }}
                    </div>
                </div>

                <div class="form-group">
                    {{ Form::label('content', __('Content'), ['class'=>'small text-muted font-italic col-form-label']) }}
                    {{ Form::textarea('content', $model->content, ['class' => 'editor-full field form-control']) }}
                </div>

            </div>
        </div>

    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">@lang('Navigation')</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>
                            <span class="small text-muted font-italic">@lang('Created')</span>
                            <span class="float-right">{{$model->created_at}}</span>
                        </p>
                        <p>
                            <span class="small text-muted font-italic">@lang('Updated')</span>
                            <span class="float-right">{{$model->updated_at}}</span>
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="@lang('Save')"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('mailings.index') }}" class="btn btn-danger w-50" title="@lang('Exit')"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

@section('scripts')
@include('template-parts.save_ajax_form')
<script src="/js/plugins/notifications/sweet_alert.min.js""></script>
<script src="/js/plugins/editors/ckeditor/ckeditor.js""></script>

<script type="text/javascript">
$(document).ready(function(){
    CKEDITOR.replaceAll('editor-full', {
        height: 400,
        extraPlugins: 'forms',
    });

    $('form').on('submit', function(e){
        e.preventDefault();
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
        save_ajax_form( $(this), "{!! route('mailings.index') !!}");
    });
});    
</script>
@endsection

resources/views/dashboard/mailings/index.blade.php
@extends('layouts.admin-layout')

@section('content')
    <div class="card mb-3">

        {{--<div class="card-body">--}}
            {{--<ul class="nav nav-tabs nav-tabs-highlight">
                <li class="nav-item"><a href="#tab-active" class="nav-link active" data-toggle="tab"><i class="icon-menu7 mr-2"></i> @lang('Active')</a></li>
            </ul>--}}
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-active">
                    <div class="table-responsive">
                        <table class="table datatable-basic table-striped dataTable no-footer w-100" id="datatableActive">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('Name')</th>
                                    <th>@lang('Group')</th>
                                    <th>@lang('Date Send')</th>
                                    <th>@lang('Sent')</th>
                                    <th>@lang('Actions')</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>

        {{--</div>--}}
    </div>

@endsection

@section('scripts')
<script>
    var language = {"url": "/js/plugins/tables/datatables/languages/{{app()->getLocale()}}.json"};
    var pageLength = {{\App\Option::getOption('rowCount',10)}};
    var columns = [
            {"data":"id"},
            {"data":"name"},
            {"data":"group"},
            {"data":"date_send"},
            {"data":"sent"},
            {"data":"actions","searchable":false,"orderable":false}
        ];
    var columnDefs = [
            { "targets": 0, "className": "text-center", },
            { "targets": 3, "className": "text-center", },
            { "targets": 4, "className": "text-center", },
            { "targets": 5, "className": "text-right", },
        ];


    var tableActive = $("#datatableActive").DataTable({
        autoWidth : true,
        responsive: true,
        processing: true,
        serverSide: true,
        pageLength: pageLength,
        // "bSortCellsTop": true,
        // "order": [[ 0, "desc" ]],
        ajax: {
            "url": "{{route('mailings.datatable')}}",
            "dataType": "json",
            "type": "POST",
            "data": {"_token":"{{ csrf_token() }}", "table":"active"},
        },
        columns:columns,
        columnDefs: columnDefs,
        language: language,
        dom: '<"datatable-header"Bfrl><"datatable-scroll"t><"datatable-footer pr-3 pl-3"ip>',
            buttons: [
                {
                    text: '<i class="icon-file-plus"></i>',
                    className: 'ml-3 btn btn-success',
                    titleAttr: '@lang('Create')',
                    action: function(e, dt, node, config) {
                        window.location.href = '{{ route('mailings.create') }}';
                    }
                }
            ]
    });

    $(document).on('click','.ajax-action',function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('href'),
            type: 'GET',
            dataType : "json",
            success: function (data) {
                tableActive.ajax.reload(null, false);
            },
            error: function(){
                console.log('Ajax error');
            }
        });
    });    

</script>
@endsection
@section('modals')
@include('template-parts.modal-ajax-destroy')
@endsection

resources/views/dashboard/mailings/show.blade.php
@extends('layouts.admin-layout')

@section('content')
<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">

        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">@lang('Preview')</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body content-area">
                {!!$model->content!!}
            </div>
        </div>
    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">@lang('Navigation')</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>
                            <span class="small text-muted font-italic">@lang('Created')</span>
                            <span class="float-right">{{$model->created_at}}</span>
                        </p>
                        <p>
                            <span class="small text-muted font-italic">@lang('Updated')</span>
                            <span class="float-right">{{$model->updated_at}}</span>
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <a href="{{ route('mailings.edit', $model->id) }}" class="btn btn-light w-50" title="{{trans('cms.btn-edit')}}"><i class="icon-pencil7"></i></a>
                            <a href="{{ route('mailings.index') }}" class="btn btn-danger w-50" title="@lang('Exit')"><i class="icon-esc"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>
@endsection