routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl();
    $parse_url = parse_url($referer, PHP_URL_PATH);
    $segments = explode('/', $parse_url);
    if (in_array($segments[1], config()->get('app.locales')) || $segments[1]=='') {
        unset($segments[1]);
    } 
    if ($lang != config()->get('app.locale')){ 
        array_splice($segments, 1, 0, $lang); 
    }
    $url = Request::root().implode("/", $segments);
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url);
})->name('setlocale');


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale(), 'middleware'=>'offline' ], function(){

    Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);

    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'isAdmin']], function() {
        Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
        Route::match(['get', 'post'],'users/message/{id}',    ['as'=>'users.message', 'uses'=>'UserController@message']);
        Route::get('users/download/{id}', ['as' => 'users.download', 'uses' => 'UserController@download']);
        Route::get('users/quiz/{id}', ['as' => 'users.quiz', 'uses' => 'UserController@quiz']);
        Route::get('users/removetestsprogress/{id}', ['as' => 'users.removetestsprogress', 'uses' => 'UserController@removeTestsProgress']);
        Route::resource('users' , 'UserController');
        Route::post('groups/detail', ['as' => 'groups.detail', 'uses' => 'GroupController@detail']);
        Route::get('groups/stat/{id}', ['as' => 'groups.stat', 'uses' => 'GroupController@stat']);
        Route::get('groups/webquestions/{id}', ['as' => 'groups.webquestions', 'uses' => 'GroupController@webquestions']);
        Route::resource('groups', 'GroupController');
        Route::resource('roles' , 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
        Route::resource('pages', 'PageController');

        Route::post( 'medias/upload', ['as'=>'medias.upload', 'uses'=>'MediaController@upload'] );
        Route::resource('medias', 'MediaController');
        Route::resource('glossaries', 'GlossaryController');
        Route::resource('mailings', 'MailingController');

        Route::resource('courses', 'CourseController');
        Route::resource('modules', 'ModuleController');
        Route::resource('lessons', 'LessonController');
        Route::resource('themes', 'ThemeController');
        Route::resource('questions', 'QuestionController');
        Route::resource('quizzes', 'QuizController');

        Route::post('/run', ['as' => 'run', 'uses' => 'AdminController@run']);
        Route::match(['get', 'post'],'/settings',  ['as'=>'settings', 'uses'=>'AdminController@settings']);
        Route::match(['get', 'post'],'/tracks',    ['as'=>'tracks',   'uses'=>'AdminController@tracks']);
        Route::post('/tracklist', ['as' => 'tracklist', 'uses' => 'AdminController@tracklist']);
        Route::get('/phpinfo', ['as' => 'phpinfo', 'uses' => 'AdminController@phpinfo']);
        // Route::get('/offline', ['as' => 'offline', 'uses' => 'AdminController@offline']);
        // Route::get('/offline/offlineCopy', ['as' => 'offlineCopy', 'uses' => 'AdminController@offlineCopy']);
    });

    # роуты для студентов

        Route::match(['get', 'post'], '/profile', ['as' => 'profile', 'middleware' => ['auth'],'uses' => 'UserController@profile']);
        Route::match(['get', 'post'], '/message', ['as' => 'message', 'middleware' => ['auth'],'uses' => 'UserController@message']);

        Route::group(['middleware' => ['auth', 'isActive', 'activity']], function() {
            Route::get('/module/{id}', ['as' => 'moduleshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@moduleshow']);
            Route::get('/theme/{id}', ['as' => 'themeshow', 'middleware' => ['isOpenTheme'],'uses' => 'UserController@themeshow']);
            Route::post('/open-next-theme', ['as' => 'opennexttheme', 'uses' => 'UserController@openNextTheme']);
            Route::get('/exam/{id}', ['as' => 'examshow', 'middleware' => [],'uses' => 'UserController@examshow']);
            Route::post('/examcheck/{id}', ['as' => 'examcheck', 'middleware' => [],'uses' => 'UserController@examcheck']);
            Route::get('/test/{id}', ['as' => 'testshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testshow']);
            Route::post('/testcheck/{id}', ['as' => 'testcheck', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testcheck']);
            Route::match(['get', 'post'], '/webquestions/{id?}', ['as' => 'webquestions', 'middleware' => [],'uses' => 'UserController@webquestions']);
            Route::match(['get', 'post'], '/homework/{id?}', ['as' => 'homework', 'middleware' => [],'uses' => 'UserController@homework']);
            Route::match(['get', 'post'], '/quiz/{id?}', ['as' => 'quizshow', 'middleware' => [],'uses' => 'UserController@quizshow']);
            Route::get('/pdf/{id}', ['as' => 'pdf', 'uses' => 'UserController@pdf']);

        });

        Route::post('/pushcounter', ['as' => 'pushcounter', 'uses' => 'UserController@pushcounter']);

    # регистрации и авторизации

        Auth::routes();
        Route::post( '/register', ['as'=>'register', 'uses'=>'GeneralController@postRegister'] );
        Route::post( '/logout',  ['as'=>'logout', 'uses'=>'GeneralController@logout'] );

    # различные страницы

        Route::get('/glossary/{character?}', ['as' => 'glossary', 'uses' => 'GeneralController@glossary']);
        Route::group(['prefix' => 'page'], function() {
            Route::get('/{page_slug}', ['as'=>'page', 'uses'=>'GeneralController@pageshow']);
        });
});

app/Lesson.php
<?php

namespace App;

use App;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Carbon\Carbon;

class Lesson extends Model implements TranslatableContract
{
    use Translatable;
    
    public $translatedAttributes = ['name'];
    protected $guarded = [];

    protected $casts = [
        'data' => 'object',
    ];

    public function module()
    {
        return $this->belongsTo('App\Module');
    }

    public function themes()
    {
        return $this->hasMany('App\Theme');
    }

    public function activeThemes()
    {
        return $this->hasMany('App\Theme')->where('activity','=',true)->orderBy('order','ASC');
    }

    public static function boot()
    {
        parent::boot();
        self::created(function($model){
            $model->data = (object)[
                    "introduction_id"=>"0",
                    "conclusion_id"=>"0"
                ];
            $model->save();
        });
    }

    static public function pluckTranslate($placeholder = 0)
    {
        $result = $placeholder ? [0=> __('Select') . ' '. __('Lesson')] : [];
        foreach (Lesson::get() as $key => $element) {
            $result[$element->id] = Option::getoption('keyOrName') ? $element->name : $element->key;
        }
        return $result;
    }

}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Traits\BreadcrumbTrait;

use App\Mail\OrderShipped;
use Illuminate\Support\Facades\Mail;

use App\User;
use App\Group;
use App\Media;
use App\Module;
use App\Option;
use App\Track;
use App\Page;
use App\Theme;
use Auth;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Storage;
use ZipArchive;

use Session;

class AdminController extends Controller 
{ 

    use BreadcrumbTrait;

    public function index()
    {
        return view('dashboard.index', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function run(Request $request)
    {
        $module = Module::findOrFail($request->module_id);
        $group_id  = $request->group_id  ? $request->group_id  : 0;
        $array = [];
        if ($module && $group_id) {
            # вытаскиваем все имеющиеся группы группы
                foreach ($module->groups as $key => $group) {
                    $array[$group->id] = [
                        'date_start'=>$group->pivot->date_start,
                        'date_finish'=>$group->pivot->date_finish,
                        'notificated'=>$group->pivot->notificated,
                    ];
                }
            # добавляем или меняем данные з формы
                if ( Carbon::parse($request->date_finish)->lt(Carbon::now()) ) {
                    unset($array[$group_id]);
                    # отправляем всем пользователям письма об остановке модуля
                        if (Option::getOption('mailModuleStop')){
                            $group = Group::find($group_id);
                            if ($group){
                                foreach ($group->users as $key => $user) {
                                    $to = $user->email;
                                    $data = [
                                        'subject' => __('Module stop'),
                                        'module' => $module->name,
                                    ];
                                    Mail::to( $to )->send(new OrderShipped($data));
                                }
                            }
                        }
                } else {
                    $array[$group_id] = [
                        'date_start'=>$request->date_start,
                        'date_finish'=>$request->date_finish,
                        'notificated'=>false,
                    ];
                    # отправляем всем пользователям письма о запуске (изменении строков работы) модуля
                        if (Option::getOption('mailModuleStop')){
                            $group = Group::find($group_id);
                            if ($group){
                                foreach ($group->users as $key => $user) {
                                    $to = $user->email;
                                    $data = [
                                        'template' => 'runmodule',
                                        'subject' => __('Module start'),
                                        'module' => $module->name,
                                        'date_start'=>$request->date_start,
                                        'date_finish'=>$request->date_finish,
                                    ];
                                    Mail::to( $to )->send(new OrderShipped($data));
                                }
                            }
                        }
                }
            # смнхронизируем
                $module->groups()->sync( $array );
            # предоставление доступа пользователям
                $group = Group::findOrFail($group_id);
                $group->openThemesForUsers();
            \App\Track::message(['moduleName'=>$module->name, 'groupName'=>$group->name, 'date1'=>$request->date_start, 'date2'=>$request->date_finish]);        
        }
        echo json_encode([
            'module_id'=>$request->module_id,
            'date_start'=>$group->getDateStart($request->module_id),
            'date_finish'=>$group->getDateFinish($request->module_id),
            'active'=>$group->ifModuleActive($request->module_id),
        ]);
    }


    public function settings(Request $request)
    {
        if ($request->isMethod('post')) {
            foreach ($request->all() as $key => $value) {
                Option::setOption($key, $value ? $value : '');
            }
            \App\Track::message();
            return redirect()->route('settings')
                ->with('flash_message', __('Settings updated successfully'));
        }        
        return view('dashboard.settings', [
            'documents' => Media::where('type','=','application')->get(),
            'users' => User::get(),
            'options' => Option::pluck('value','key'),
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function tracks(Request $request)
    {
        if ($request->isMethod('post')) {
            Track::truncate();
            \App\Track::message();
            return redirect()->route('tracks')
                ->with('flash_message', __('Event Log was cleared'));
        }        
        return view('dashboard.tracks', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    public function tracklist(Request $request)
    {
        $where = [];
        $columns = [
            0 => 'created_at',
            1 => 'user_id',
            2 => 'ip',
            3 => 'name',
        ];

        $totalData = Track::where($where)->count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if(empty($request->input('search.value'))){
            $temp = Track::where($where)->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $totalFiltered = $totalData;
        } else {
            $search = $request->input('search.value');
            $temp = Track::where($where)->where('name','like',"%{$search}%")
                ->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $temp = Track::where($where)->where('name','like',"%{$search}%");
                $totalFiltered = $temp->count();
        }
        
        $data = [];
        if($models){
            foreach($models as $model){
                $nestedData['date'] = $model->created_at->format('d.m.Y H:i:s');
                $user = User::find($model->user_id);
                $nestedData['user'] = $model->user_id==-1 ? __('System') : ($user ? $user->name : __('Unknown'));
                $nestedData['ip'] = $model->ip;
                $nestedData['name'] = $model->name;
                $data[] = $nestedData;
            }
        }
        $json_data = [
            "draw" => (int)$request->input('draw'),
            "recordsTotal" => (int)$totalData,
            "recordsFiltered" => (int)$totalFiltered,
            "data" => $data,

        ];
        echo json_encode($json_data);
    }

    # делаем правильную ссылку для оффлайна
    function offlineUri($uri = '', $prefix = '')
    {
        $result = $uri;
        $base_url = route('home');
        $new_uri  = str_replace($base_url, '', $uri);
        if ($uri != $new_uri){
            $links = explode('/',$new_uri);
            if (count($links)==1) {$new_uri='index';}
            if (strpos($new_uri, '.') === false) {$new_uri .= '.html';}
            if (substr($new_uri,0,1)=='/') {$new_uri=substr($new_uri,1);}
            $result = $prefix . $new_uri;
        }
        return $result;
    }

    # получение контента по урлу
    public function getDataFromUrl($url, $level=0)
    {
        # получаем данные из файла
            $opts = [
                'http' => [
                    'method' => "GET",
                    'header' => "Accept-language: ".\App::getLocale()."\r\n"
                ]
            ];
            $context = stream_context_create($opts);
            for ($i=0; $i < 10; $i++) { 
                $html_request = @file_get_contents($url, false, $context);
                if ($html_request!==false){
                    break;
                }
            }
        # создаем префикс
            $prefix = '';
            for ($i=0; $i < $level; $i++) { 
                $prefix .= '../';
            }
        # меняем пути для ассетов
            $source  = [ '/css/', '/assets/', '/js/', '../../../storage', '/storage/' ];
            $replace = [ $prefix . 'css/', $prefix . 'assets/', $prefix . 'js/', $prefix . 'storage/', $prefix . 'storage/' ];
            $result = str_replace($source, $replace, $html_request);
        # находи все ссылки и меняем их на локальные, 
            preg_match_all('|href="([^"]*)"|U',$result,$matches); # простые ссылки
            foreach ($matches[1] as $key => $match) {
                $matches[2][$key] = 'href="' . $this->offlineUri($match,$prefix) . '"';
                $result = str_replace($matches[0][$key], $matches[2][$key], $result);
            }

        return $result;
    }

    # phpinfo
    public function phpinfo()
    {
        return view('dashboard.phpinfo', [
            'data' => self::getBreadcrumb(),
        ]);
    }

}

resources/views/dashboard/lessons/form.blade.php
@extends('layouts.admin-layout')

@section('content')

{{ Form::model($model, array('url' => $model->id ? route('lessons.update', $model->id) : route('lessons.store'), 'method' => $model->id ? 'PUT' : 'POST')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header bg-transparent header-elements-inline">
                <h5 class="card-title">@lang('Parameters')</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">

                <div class="tab-content">
                    <!-- General tab -->
                    <div class="tab-pane fade show active" id="general">
                        <div class="form-group row">
                            {{ Form::label('key', __('Key'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                            <div class="col-md-8">
                                {{ Form::text('key', null, array('class' => 'field form-control')) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('module_id', __('Module'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                            <div class="col-md-8">
                                {{ Form::select('module_id', $modules, null, array('class' => 'field form-control')) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('introduction_id', __('Introduction'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                            <div class="col-md-8">
                                {{ Form::select('introduction_id', $pages, isset($model->data->introduction_id) ? $model->data->introduction_id : 0, array('class' => 'field form-control')) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('conclusion_id', __('Conclusion'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                            <div class="col-md-8">
                                {{ Form::select('conclusion_id', $pages, isset($model->data->conclusion_id) ? $model->data->conclusion_id : 0, array('class' => 'field form-control')) }}
                            </div>
                        </div>

                        @if(count(config()->get('app.locales'))>1)
                            <ul class="nav nav-tabs nav-tabs-highlight">
                                @foreach(config()->get('app.locales') as $key => $language)
                                    <li class="nav-item"><a href="#tab-{{$language}}" class="nav-link @if($key==0) active @endif" data-toggle="tab"><img src="/assets/img/lang/{{$language}}.png" alt="" class="img-flag mr-2"> @lang($language)</a></li>
                                @endforeach
                            </ul>
                        @endif
                        <div class="tab-content">
                            @foreach(config()->get('app.locales') as $key => $language)
                                <div class="tab-pane fade @if($key==0) show active @endif" id="tab-{{$language}}">
                                    <div class="form-group row">
                                        {{ Form::label('name-'.$language, __('Name'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                                        <div class="col-sm-8">
                                            {{ Form::text('name-'.$language, (isset($model->translate($language)->name) ? $model->translate($language)->name : null), ['class' => 'field form-control']) }}
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <!-- /general tab -->
                </div>

            </div>
        </div>

    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">@lang('Navigation')</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>
                            <span class="small text-muted font-italic">@lang('Created')</span>
                            <span class="float-right">{{$model->created_at}}</span>
                        </p>
                        <p>
                            <span class="small text-muted font-italic">@lang('Updated')</span>
                            <span class="float-right">{{$model->updated_at}}</span>
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="@lang('Save')"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('lessons.index') }}" class="btn btn-danger w-50" title="@lang('Exit')"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

@section('scripts')
@include('template-parts.save_ajax_form')
<script src="/js/plugins/notifications/sweet_alert.min.js""></script>

<script type="text/javascript">
$(document).ready(function(){
    $('form').on('submit', function(e){
        e.preventDefault();
        save_ajax_form( $(this), "{!! route('lessons.index') !!}");
    });
});    
</script>
@endsection

resources/views/dashboard/lessons/index.blade.php
@extends('layouts.admin-layout')

@section('content')
    <div class="card mb-3">

        <div class="pl-3 pt-3 pr-3">
            <div class="row search-panel">
                <div class="col-lg-6">
                    <div class="form-group row mb-0">
                        <label for="" class="col-form-label col-sm-2">@lang('Module')</label>
                        <div class="col-sm-10">
                            <select id="module_id" class="form-control">
                                <option value="0">@lang('All Modules')</option>
                                @foreach($modules as $key => $module)
                                    <option value="{{$key}}">{{$module}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-active">
                    <div class="table-responsive">
                        <table class="table datatable-basic table-striped dataTable no-footer w-100" id="datatableActive">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('Name')</th>
                                    <th>@lang('Module')</th>
                                    <th>@lang('Themes')</th>
                                    <th>@lang('Active Themes')</th>
                                    <th>@lang('Actions')</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>

    </div>

@endsection

@section('scripts')
<script>
    var language = {"url": "/js/plugins/tables/datatables/languages/{{app()->getLocale()}}.json"};
    var pageLength = {{\App\Option::getOption('rowCount',10)}};
    var columns = [
            {"data":"id"},
            {"data":"name"},
            {"data":"module"},
            {"data":"themes"},
            {"data":"activethemes"},
            {"data":"actions","searchable":false,"orderable":false}
        ];
    var columnDefs = [
            { "targets": 0, "className": "text-center", },
            { "targets": 3, "className": "text-center", },
            { "targets": 4, "className": "text-center", },
            { "targets": 5, "className": "text-right", },
        ];


    var tableActive = $("#datatableActive").DataTable({
        autoWidth : true,
        responsive: true,
        processing: true,
        serverSide: true,
        pageLength: pageLength,
        // "bSortCellsTop": true,
        // "order": [[ 0, "desc" ]],
        ajax: {
            "url": "{{route('lessons.datatable')}}",
            "dataType": "json",
            "type": "POST",
            "data": function ( d ) {
                d._token = "{{ csrf_token() }}";
                d.module_id = $('#module_id').val();
                d.table = "active";
            }            
        },
        columns:columns,
        columnDefs: columnDefs,
        language: language,
        dom: '<"datatable-header"Bfrl><"datatable-scroll"t><"datatable-footer pr-3 pl-3"ip>',
            buttons: [
                {
                    text: '<i class="icon-file-plus"></i>',
                    className: 'ml-3 btn btn-success',
                    titleAttr: '@lang('Create')',
                    action: function(e, dt, node, config) {
                        window.location.href = '{{ route('lessons.create') }}';
                    }
                }
            ]
    });

    $('div.search-panel').on('change','select',function(e){
        tableActive.ajax.reload(null, false);
    })

</script>
@endsection
@section('modals')
@include('template-parts.modal-ajax-destroy')
@endsection