routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl();
    $parse_url = parse_url($referer, PHP_URL_PATH);
    $segments = explode('/', $parse_url);
    if (in_array($segments[1], config()->get('app.locales')) || $segments[1]=='') {
        unset($segments[1]);
    } 
    if ($lang != config()->get('app.locale')){ 
        array_splice($segments, 1, 0, $lang); 
    }
    $url = Request::root().implode("/", $segments);
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url);
})->name('setlocale');


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale(), 'middleware'=>'offline' ], function(){

    Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);

    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'isAdmin']], function() {
        Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
        Route::match(['get', 'post'],'users/message/{id}',    ['as'=>'users.message', 'uses'=>'UserController@message']);
        Route::get('users/download/{id}', ['as' => 'users.download', 'uses' => 'UserController@download']);
        Route::get('users/quiz/{id}', ['as' => 'users.quiz', 'uses' => 'UserController@quiz']);
        Route::get('users/removetestsprogress/{id}', ['as' => 'users.removetestsprogress', 'uses' => 'UserController@removeTestsProgress']);
        Route::resource('users' , 'UserController');
        Route::post('groups/detail', ['as' => 'groups.detail', 'uses' => 'GroupController@detail']);
        Route::get('groups/stat/{id}', ['as' => 'groups.stat', 'uses' => 'GroupController@stat']);
        Route::get('groups/webquestions/{id}', ['as' => 'groups.webquestions', 'uses' => 'GroupController@webquestions']);
        Route::resource('groups', 'GroupController');
        Route::resource('roles' , 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
        Route::resource('pages', 'PageController');

        Route::post( 'medias/upload', ['as'=>'medias.upload', 'uses'=>'MediaController@upload'] );
        Route::resource('medias', 'MediaController');
        Route::resource('glossaries', 'GlossaryController');
        Route::resource('mailings', 'MailingController');

        Route::resource('courses', 'CourseController');
        Route::resource('modules', 'ModuleController');
        Route::resource('lessons', 'LessonController');
        Route::resource('themes', 'ThemeController');
        Route::resource('questions', 'QuestionController');
        Route::resource('quizzes', 'QuizController');

        Route::post('/run', ['as' => 'run', 'uses' => 'AdminController@run']);
        Route::match(['get', 'post'],'/settings',  ['as'=>'settings', 'uses'=>'AdminController@settings']);
        Route::match(['get', 'post'],'/tracks',    ['as'=>'tracks',   'uses'=>'AdminController@tracks']);
        Route::post('/tracklist', ['as' => 'tracklist', 'uses' => 'AdminController@tracklist']);
        Route::get('/phpinfo', ['as' => 'phpinfo', 'uses' => 'AdminController@phpinfo']);
        // Route::get('/offline', ['as' => 'offline', 'uses' => 'AdminController@offline']);
        // Route::get('/offline/offlineCopy', ['as' => 'offlineCopy', 'uses' => 'AdminController@offlineCopy']);
    });

    # роуты для студентов

        Route::match(['get', 'post'], '/profile', ['as' => 'profile', 'middleware' => ['auth'],'uses' => 'UserController@profile']);
        Route::match(['get', 'post'], '/message', ['as' => 'message', 'middleware' => ['auth'],'uses' => 'UserController@message']);

        Route::group(['middleware' => ['auth', 'isActive', 'activity']], function() {
            Route::get('/module/{id}', ['as' => 'moduleshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@moduleshow']);
            Route::get('/theme/{id}', ['as' => 'themeshow', 'middleware' => ['isOpenTheme'],'uses' => 'UserController@themeshow']);
            Route::post('/open-next-theme', ['as' => 'opennexttheme', 'uses' => 'UserController@openNextTheme']);
            Route::get('/exam/{id}', ['as' => 'examshow', 'middleware' => [],'uses' => 'UserController@examshow']);
            Route::post('/examcheck/{id}', ['as' => 'examcheck', 'middleware' => [],'uses' => 'UserController@examcheck']);
            Route::get('/test/{id}', ['as' => 'testshow', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testshow']);
            Route::post('/testcheck/{id}', ['as' => 'testcheck', 'middleware' => ['isOpenModule'],'uses' => 'UserController@testcheck']);
            Route::match(['get', 'post'], '/webquestions/{id?}', ['as' => 'webquestions', 'middleware' => [],'uses' => 'UserController@webquestions']);
            Route::match(['get', 'post'], '/homework/{id?}', ['as' => 'homework', 'middleware' => [],'uses' => 'UserController@homework']);
            Route::match(['get', 'post'], '/quiz/{id?}', ['as' => 'quizshow', 'middleware' => [],'uses' => 'UserController@quizshow']);
            Route::get('/pdf/{id}', ['as' => 'pdf', 'uses' => 'UserController@pdf']);

        });

        Route::post('/pushcounter', ['as' => 'pushcounter', 'uses' => 'UserController@pushcounter']);

    # регистрации и авторизации

        Auth::routes();
        Route::post( '/register', ['as'=>'register', 'uses'=>'GeneralController@postRegister'] );
        Route::post( '/logout',  ['as'=>'logout', 'uses'=>'GeneralController@logout'] );

    # различные страницы

        Route::get('/glossary/{character?}', ['as' => 'glossary', 'uses' => 'GeneralController@glossary']);
        Route::group(['prefix' => 'page'], function() {
            Route::get('/{page_slug}', ['as'=>'page', 'uses'=>'GeneralController@pageshow']);
        });
});

resources/views/menu/app-breadcrumb.blade.php
<div class="breadcrumb">
    <a href="{{route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> @lang('Home')</a>
    @if(isset($data->breadcrumbs))
        @foreach($data->breadcrumbs as $key => $breadcrumb)
            @if (count($data->breadcrumbs)!=$key+1)
                <a href="{{$breadcrumb['url']}}" class="breadcrumb-item">{!!$breadcrumb['title']!!}</a>
            @else
                <span class="breadcrumb-item active">{!!$breadcrumb['title']!!}</span>
            @endif
        @endforeach
    @endif
</div>

resources/views/menu/app-login-form.blade.php
<div class="card card-sidebar-mobile">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">@lang('Authorization')</h6>
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('login') }}">
            @csrf
            <input id="email" type="email" class="form-control @if(isset($errors)) @error('email') is-invalid @enderror @endif mb-3" name="email" value="{{ old('email') }}" required autocomplete="email" Placeholder="@lang('Email')" autofocus>
            @if(isset($errors)) @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror @endif
            <input id="password" type="password" class="form-control @if(isset($errors)) @error('password') is-invalid @enderror @endif mb-3" name="password" required autocomplete="current-password" Placeholder="@lang('Password')">
            @if(isset($errors)) @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror @endif
            <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>
                <label class="custom-control-label" for="remember">@lang('Remember Me')</label>
            </div>
            <button type="submit" class="btn btn-primary form-control mb-3">@lang('Login')</button>
            <div class="text-center">
                @if (Route::has('password.request'))
                    <a href="{{ route('password.request') }}">
                        @lang('Forgot Your Password?')
                    </a>
                @endif/
                @if (Route::has('register'))
                    <a href="{{ route('register') }}">
                        @lang('Register')
                    </a>
                @endif
            </div>
        </form>
    </div>
</div>

resources/views/menu/app-modules-themes.blade.php
@if(auth()->user()->activity)

    @foreach(auth()->user()->groups as $key => $group)
        @foreach($group->modules as $key2 => $module)
            @if( \Carbon\Carbon::parse($module->pivot->date_finish)->gte( \Carbon\Carbon::now()  ) )
                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link module-{{$module->id}}">{{--<i class="icon-stack"></i> --}}{{--<span>{{$module->name}}</span>--}}<span><div>{{$module->name}}</div><div class="text-danger">@lang('Active before') {{\Carbon\Carbon::parse($module->pivot->date_finish)->format('d.m.Y')}}</div></span><span class="badge {{ isset(auth()->user()->data->modules->{$module->id}->passed) ? 'bg-success' : 'bg-warning' }} ml-auto passed">{{ auth()->user()->openThemesPercent($module->id) }}%</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="{{$module->name}}">
                        <!-- Introduction -->
                            @if(isset($module->data->introduction_id) && $module->data->introduction_id)
                                <li class="nav-item"><a href="{{route('page',$module->data->introduction_id)}}" class="nav-link introduction-{{$module->id}} {{ \Request::url() == route('page',$module->data->introduction_id) ? 'active' : ''}}"><span>@lang('Introduction')</span></a></li>
                            @endif
                        <!-- /introduction -->
                        <!-- Lessons & Themes -->
                            @foreach($module->lessons as $key3 => $lesson)
                                <li class="nav-item nav-item-submenu">
                                    <a href="#" class="nav-link">{{$lesson->name}}</a>
                                    <ul class="nav nav-group-sub">
                                        <!-- Introduction -->
                                            @if(isset($lesson->data->introduction_id) && $lesson->data->introduction_id)
                                                <li class="nav-item"><a href="{{route('page',$lesson->data->introduction_id)}}" class="nav-link introduction-{{$lesson->id}} {{ \Request::url() == route('page',$lesson->data->introduction_id) ? 'active' : ''}}"><span>@lang('Introduction')</span></a></li>
                                            @endif
                                        <!-- /introduction -->
                                        @foreach($lesson->activeThemes as $key3 => $theme)
                                            <li class="nav-item"><a href="{{route('themeshow',$theme->id)}}" class="nav-link {{ auth()->user()->ifActiveTheme($theme->id) ? '' : 'disabled' }} theme-{{$theme->id}} {{\Request::url() == route('themeshow',$theme->id) ? 'active' : ''}}"><span>{!!$theme->ifThemePassed() ? '<i class="icon-checkmark2 mr-1"></i> ' : ''!!}{{$theme->name}}</span></a></li>
                                        @endforeach
                                        <!-- Conclusion -->
                                            @if(isset($lesson->data->conclusion_id) && $lesson->data->conclusion_id)
                                                <li class="nav-item"><a href="{{route('page',$lesson->data->conclusion_id)}}" class="nav-link conclusion-{{$lesson->id}} {{ \Request::url() == route('page',$lesson->data->conclusion_id) ? 'active' : ''}}"><span>@lang('Conclusion')</span></a></li>
                                            @endif
                                        <!-- /conclusion -->
                                    </ul>
                                </li>
                            @endforeach
                        <!-- /lessons & themes -->
                        <!-- Conclusion -->
                            @if(isset($module->data->conclusion_id) && $module->data->conclusion_id)
                                <li class="nav-item"><a href="{{route('page',$module->data->conclusion_id)}}" class="nav-link conclusion-{{$module->id}} {{ \Request::url() == route('page',$module->data->conclusion_id) ? 'active' : ''}}"><span>@lang('Conclusion')</span></a></li>
                            @endif
                        <!-- /conclusion -->
                        <!-- Literature -->
                            @if(isset($module->data->literature_id) && $module->data->literature_id)
                                <li class="nav-item"><a href="{{route('page',$module->data->literature_id)}}" class="nav-link literature-{{$module->id}} {{ \Request::url() == route('page',$module->data->literature_id) ? 'active' : ''}}"><span>@lang('Literature')</span></a></li>
                            @endif
                        <!-- /literature -->
                        <!-- Webquestions -->
                            @if(isset($module->data->webquestions) && $module->data->webquestions)
                                <li class="nav-item"><a href="{{route('webquestions',$module->id)}}" class="nav-link webquestions-{{$module->id}} {{ \Request::url() == route('webquestions',$module->id) ? 'active' : ''}}"><span>@lang('Questions to the Webinar')</span></a></li>
                            @endif
                        <!-- /webquestions -->
                        <!-- Test -->
                            <li class="nav-item"><a href="{{route('testshow',$module->id)}}" class="nav-link test-{{$module->id}} {{ auth()->user()->ifOpenTest($module->id) ? '' : 'disabled' }} {{\Request::url() == route('testshow',$module->id) ? 'active' : ''}}"><span>@lang('Module Test')</span></a></li>
                        <!-- /test -->
                        <!-- Homework -->
                            @if(isset($module->data->homework) && $module->data->homework)
                                <li class="nav-item"><a href="{{route('homework',$module->id)}}" class="nav-link homework-{{$module->id}} {{isset(auth()->user()->data->modules->{$module->id}->passed) ? '' : 'disabled' }} {{ \Request::url() == route('homework',$module->id) ? 'active' : ''}}"><span>@lang('Homework')</span></a></li>
                            @endif
                        <!-- /homework -->
                    </ul>
                </li>

            @endif
        @endforeach
    @endforeach

    @foreach( \App\Course::get() as $key => $course)
        @if(auth()->user()->ifOpenExam($course->id))
            <li class="nav-item"><a href="{{route('examshow',$course->id)}}" class="nav-link exam-{{$module->id}} {{\Request::url() == route('examshow',$course->id) ? 'active' : ''}}"><span>@lang('Course Exam')</span></a></li>
        @endif
    @endforeach

    @foreach(auth()->user()->groups as $key => $group)
        @foreach($group->quizzes as $key2 => $quiz)
            <li class="nav-item"><a href="{{route('quizshow',$quiz->id)}}" class="nav-link quiz-{{$quiz->id}} {{\Request::url() == route('quizshow',$quiz->id) ? 'active' : ''}}"><i class="icon-clipboard2"></i> <span>{{$quiz->name}}</span></a></li>
        @endforeach
    @endforeach
@endif

resources/views/menu/app-user-menu.blade.php
                        <div class="sidebar-user">
                            <div class="card-body">
                                <div class="media">
                                    <div class="mr-3">
                                        <a href="{{ route('profile') }}"><img src="{{ auth()->user()->getAvatar() }}" width="38" height="38" class="rounded-circle" alt=""></a>
                                    </div>

                                    <div class="media-body">
                                        <div class="media-title font-weight-semibold">{{Auth::user()->name}}</div>
                                        <div class="font-size-xs opacity-50">{{Auth::user()->position}}</div>
                                        @if(!Auth::user()->activity)
                                            <div class="font-size-xs text-danger">@lang('Blocked')</div>
                                        @endif
                                    </div>

                                    <div class="ml-3 align-self-center">
                                        <a href="#" class="dropdown-toggle caret-0" data-toggle="dropdown" aria-expanded="false"><i class="icon-cog3"></i></a>
                                        <div class="dropdown-menu dropdown-menu-left">
                                            <a href="{{ route('profile') }}" class="dropdown-item"><i class="icon-user"></i>@lang('Profile')</a>
                                            <a href="{{ route('message') }}" class="dropdown-item"><i class="icon-comment-discussion"></i>@lang('Message List')</a>
                                            <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="icon-switch2"></i>@lang('Logout')</a>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>

                                            {{--<a href="#" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>--}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

resources/views/menu/breadcrumb.blade.php
<div class="breadcrumb">
    @if(isset($data['breadcrumbs']))
        @foreach($data['breadcrumbs'] as $key => $breadcrumb)
            @if (count($data['breadcrumbs'])!=$key+1)
                <a href="{{$breadcrumb['url']}}" class="breadcrumb-item">{!!$breadcrumb['title']!!}</a>
            @else
                <span class="breadcrumb-item active">{!!$breadcrumb['title']!!}</span>
            @endif
        @endforeach
    @else
        <a href="{{route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item active">Dashboard</span>
    @endif
</div>

resources/views/menu/profile-menu.blade.php
<ul class="nav nav-sidebar">
    <li class="nav-item">
        <a href="{{route('profile')}}" class="nav-link">
            <i class="icon-user-plus"></i>
            <span>@lang('My profile')</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="#" class="nav-link" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="icon-switch2"></i>
            <span>@lang('Logout')</span>
        </a>
    </li>
</ul>

resources/views/menu/sidebar-menu.blade.php
<ul class="nav nav-sidebar" data-nav-type="accordion">
    <li class="nav-item">
        <a href="{{route('dashboard')}}" class="nav-link {!! \Request::url() == route('dashboard') ? 'active' : '' !!}">
            <i class="icon-equalizer3"></i><span>@lang('Dashboard')</span>
        </a>
    </li>
    @if(Gate::check('admin') || Gate::check('users') || Gate::check('groups'))
        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-users"></i> <span>@lang('Users')</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="@lang('Users')">
                @if(Gate::check('admin') || Gate::check('users'))
                    <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {!! \Request::url() == route('users.index') ? 'active' : '' !!}">@lang('User list')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('groups'))
                    <li class="nav-item"><a href="{{ route('groups.index') }}" class="nav-link {!! \Request::url() == route('groups.index') ? 'active' : '' !!}">@lang('Groups')</a></li>
                @endif
            </ul>
        </li>
    @endif
    @if(Gate::check('admin') || Gate::check('pages') || Gate::check('medias') || Gate::check('glossaries'))
        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-display"></i> <span>@lang('Settings')</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="@lang('Settings')">
                @if(Gate::check('admin') || Gate::check('pages'))
                    <li class="nav-item"><a href="{{ route('pages.index') }}" class="nav-link {!! \Request::url() == route('pages.index') ? 'active' : '' !!}">@lang('Pages')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('medias'))
                    <li class="nav-item"><a href="{{ route('medias.index') }}" class="nav-link {!! \Request::url() == route('medias.index') ? 'active' : '' !!}">@lang('Media')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('glossaries'))
                    <li class="nav-item"><a href="{{ route('glossaries.index') }}" class="nav-link {!! \Request::url() == route('glossaries.index') ? 'active' : '' !!}">@lang('Glossary')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('mailings'))
                    <li class="nav-item"><a href="{{ route('mailings.index') }}" class="nav-link {!! \Request::url() == route('mailings.index') ? 'active' : '' !!}">@lang('Mailings')</a></li>
                @endif
            </ul>
        </li>
    @endif
    @if(Gate::check('admin') || Gate::check('courses') || Gate::check('modules') || Gate::check('lessons') || Gate::check('themes') || Gate::check('questions') || Gate::check('quizzes'))
        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-tree7"></i> <span>@lang('Modules') & @lang('Themes')</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="@lang('Modules') & @lang('Themes')">
                @if(Gate::check('admin') || Gate::check('courses'))
                    <li class="nav-item"><a href="{{ route('courses.index') }}" class="nav-link {!! \Request::url() == route('courses.index') ? 'active' : '' !!}">@lang('Courses')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('modules'))
                    <li class="nav-item"><a href="{{ route('modules.index') }}" class="nav-link {!! \Request::url() == route('modules.index') ? 'active' : '' !!}">@lang('Modules')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('lessons'))
                    <li class="nav-item"><a href="{{ route('lessons.index') }}" class="nav-link {!! \Request::url() == route('lessons.index') ? 'active' : '' !!}">@lang('Lessons')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('themes'))
                    <li class="nav-item"><a href="{{ route('themes.index') }}" class="nav-link {!! \Request::url() == route('themes.index') ? 'active' : '' !!}">@lang('Themes')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('questions'))
                    <li class="nav-item"><a href="{{ route('questions.index') }}" class="nav-link {!! \Request::url() == route('questions.index') ? 'active' : '' !!}">@lang('Questions')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('quizzes'))
                    <li class="nav-item"><a href="{{ route('quizzes.index') }}" class="nav-link {!! \Request::url() == route('quizzes.index') ? 'active' : '' !!}">@lang('Quizzes')</a></li>
                @endif
            </ul>
        </li>
    @endif
    @if(Gate::check('admin') || Gate::check('offline'))
        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-cog"></i> <span>@lang('Options')</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="@lang('Options')">
                @if(Gate::check('admin'))
                    <li class="nav-item"><a href="{{ route('roles.index') }}" class="nav-link {!! \Request::url() == route('roles.index') ? 'active' : '' !!}">@lang('Roles')</a></li>
                    <li class="nav-item"><a href="{{ route('permissions.index') }}" class="nav-link {!! \Request::url() == route('permissions.index') ? 'active' : '' !!}">@lang('Permissions')</a></li>
                    <li class="nav-item"><a href="{{ route('settings') }}" class="nav-link {!! \Request::url() == route('settings') ? 'active' : '' !!}">@lang('Settings')</a></li>
                    <li class="nav-item"><a href="{{ route('tracks') }}" class="nav-link {!! \Request::url() == route('tracks') ? 'active' : '' !!}">@lang('Event Log')</a></li>
                    <li class="nav-item"><a href="{{ route('phpinfo') }}" class="nav-link {!! \Request::url() == route('phpinfo') ? 'active' : '' !!}">@lang('About System')</a></li>
                @endif
                @if(Gate::check('admin') || Gate::check('offline'))
                    {{--<li class="nav-item"><a href="{{ route('offline') }}" class="nav-link {!! \Request::url() == route('offline') ? 'active' : '' !!}">@lang('Offline Version Creating')</a></li>--}}
                @endif
            </ul>
        </li>
    @endif

</ul>